Repository Asiatik/codezilla, pull requests merged in 2018-09, with the labels that each got.

#30 Heap_Sort.cpp
  Sorting/C++/Heap_Sort.cpp
Labels: Code Review Request

#35 Implemenation of Merge sort for arrays (issue #31)
  Sorting/C++/MergeSort_Arrays/MergeSortArray.cpp
  Sorting/C++/MergeSort_Arrays/MergeSortArray.h
  Sorting/C++/MergeSort_Arrays/MergeSort_ArrayTest.cpp
Labels: Code Review Request

#40 Creating explicit LICENSE (Issue 41)
  LICENSE
Labels: Code Review Request

#43 Added Binary Search implementations in C, C++, Java and Python (Issue 42)
  Searching/Binary_Search/C++/BinarySearch.cpp
  Searching/Binary_Search/C/BinarySearch.c
  Searching/Binary_Search/Java/BinarySearch.java
  Searching/Binary_Search/Python/BinarySearch.py
  Searching/Binary_Search/README.md
Labels: Code Changes Required, c++, java

#50 Added Contributing.md (Issue 49)
  CONTRIBUTING.md
  LICENSE
  README.md
Labels: Code Changes Required
